// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzNOHij-GWfBfRPgxN9t14BlnGggSnzdY',
    appId: '1:1061779726670:web:32de5ac14dbcaf39bcfe1f',
    messagingSenderId: '1061779726670',
    projectId: 'tawssel-79811',
    authDomain: 'tawssel-79811.firebaseapp.com',
    storageBucket: 'tawssel-79811.appspot.com',
    measurementId: 'G-6MSHHX8CC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTBjw9NEiuL0G14c9hhWcFZqgx37M8kDI',
    appId: '1:1061779726670:android:8371222721b68a3bbcfe1f',
    messagingSenderId: '1061779726670',
    projectId: 'tawssel-79811',
    storageBucket: 'tawssel-79811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ClCQKJ7Wiu6oLNBLIQR5B4wyU1a-rtw',
    appId: '1:1061779726670:ios:c57999397798b6b2bcfe1f',
    messagingSenderId: '1061779726670',
    projectId: 'tawssel-79811',
    storageBucket: 'tawssel-79811.appspot.com',
    iosBundleId: 'com.example.task',
  );
}
